---
driver:
  name: vagrant
  vm_hostname: verdaccio-vagrant
  customize:
    memory: 512
    natdnsproxy1: 'on'
    natdnshostresolver1: 'on'

platforms:
- name: ubuntu/precise64
- name: ubuntu/trusty64
- name: centos/6
- name: centos/7
##########################################################################
# See <https://github.com/test-kitchen/kitchen-ec2> for more documentation
# on kitchen-ec2
##########################################################################
#- name: amazon-2018.03
#  driver:
#    name: ec2

provisioner:
  name: chef_zero
  product_name: chef

suites:
- name: default
  run_list:
    - recipe[verdaccio]
  attributes:
    verdaccio:
      listen: :4873
